### ISSUE TITLE
Regarding errors encountered during visualization

### ISSUE THREAD

**Issue by LongJi12** [gywns6287/BAAM#3]
After I finish training, run the visualization code Python vis_ Apollo.py -- output/ Outputs -- file 171206_ 081122658_ Camera_ 5-- Save vis_ Results, it will display "Traceback (most recent call last):"

File "/home/long. ji/project/BAAM/vis/vis-apolo. py", line 70, in<module>

Vis.mesh_ Show_ Back_ Face()

File "/home/long. ji/project/BAAM/vis/utilities. py", line 94, in mesh_ Show_ Back_ Face

Self__ Vis.get_ Render_ Option(). mesh_ Show_ Back_ Face=True

AttributeError: 'NoneType' object has no attribute 'mesh_ Show_ Back_ Face

Segmentation fault (core dumped)“

**Comment by CYZ-zhe** [comment]
Hello, why is there more than 1000 pictures in the val data set I downloaded, but there are only 200 marks downloaded from the web disk, and the id of these 200 marks does not correspond to the id of the picture? Did this article use the 200 pictures of the training set as the validation set.

**Comment by gywns6287** [comment]
Yes, we split whole train images to train/val data set following official split list. I am attaching the split list we used for explements.

-----------------------------------------------
충남대학교 컴퓨터비전 연구실 이 효 준
Hyo-Jun Lee, Ph.D.
Computer vision lab., Chungnam National University.

-----Original Message-----

**Comment by gywns6287** [comment]
@LongJi12 It is typically the result of a lack of available memory. One suggestion is to reduce the number of objects ('dts' in the script) in vis_apollo.py.
