### ISSUE TITLE
About camera internal and external parameters

### ISSUE THREAD

**Issue by LongJi12** [gywns6287/BAAM#4]
Hello, dear author！how do you get the internal and external parameters of the camera in the view_point_3d.json file? I want to re-adjust the camera parameters based on my own data set. How can I achieve this?Thank you!!

**Comment by gywns6287** [comment]
Hi. You can get a camera paramters' file by adding  "vis.save_view_point('new_camera.json')" in line 72 of 'vis_apollo.py'.

Here are example code lines.
```
70    vis.load_view_point("view_point_3d.json")
71    vis.run()
72    vis.save_view_point('new_camera.json')
73    vis.capture_screen_image(os.path.join(args.save, f'{args.file}.3d.png'))
```

After adjusting a view point by Open3D UI, you  just exit the Open3D window. Then, a new camera parameters of your own view points  will be saved in 'new_camera.json'

**Comment by LongJi12** [comment]
> Hi. You can get a camera paramters' file by adding "vis.save_view_point('new_camera.json')" in line 72 of 'vis_apollo.py'.
> 
> Here are example code lines.
> 
> ```
> 70    vis.load_view_point("view_point_3d.json")
> 71    vis.run()
> 72    vis.save_view_point('new_camera.json')
> 73    vis.capture_screen_image(os.path.join(args.save, f'{args.file}.3d.png'))
> ```
> 
> After adjusting a view point by Open3D UI, you just exit the Open3D window. Then, a new camera parameters of your own view points will be saved in 'new_camera.json'

Thanks! ! I successfully got the new json. I have another question, how to project the mesh onto the original image?Looking forward to your answer！
