### ISSUE TITLE
Get the mesh on the original image

### ISSUE THREAD

**Issue by LongJi12** [gywns6287/BAAM#8]
Hello! it’s me again,!how can I render mesh on the original image?That is, the corresponding position of the generated mesh in the original image. I have been troubled by the corresponding position of the generated mesh in the original image for a long time, and I sincerely hope to get your answer.！The effect is the same as in your paper：
![image](https://github.com/gywns6287/BAAM/assets/147734830/428075b6-f61f-437d-9979-64eddb758449)

**Comment by danieldimit** [comment]
Could you please post your projection over the image code if you've implemented it and still keep it?
